global using Carter;
global using AutoMapper;
global using MediatR;
global using BuildingBlocks.CQRS;
global using Catalog.API.Models;
global using Marten;
global using FluentValidation;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Handlers;